#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_HELLO_WORLD_PINS_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_HELLO_WORLD_PINS_H_

const int buzzerPin = D2;

#endif  // TENSORFLOW_LITE_MICRO_EXAMPLES_HELLO_WORLD_PINS_H_